<?php

// Ini adalah file konfigurasi yang benar untuk filament-lexical-editor.
// Pastikan file Anda bernama persis "filament-lexical-editor.php"
// dan berada di dalam folder "config".

return [
    'fontFamily' => [
        // Sans-Serif Fonts
        'Arial' => 'Arial',
        'Arial Black' => 'Arial Black',
        'Calibri' => 'Calibri',
        'Candara' => 'Candara',
        'Century Gothic' => 'Century Gothic',
        'Franklin Gothic Medium' => 'Franklin Gothic Medium',
        'Futura' => 'Futura',
        'Geneva' => 'Geneva',
        'Gill Sans' => 'Gill Sans',
        'Helvetica' => 'Helvetica',
        'Impact' => 'Impact',
        'Inter' => 'Inter',
        'Lato' => 'Lato',
        'Lucida Grande' => 'Lucida Grande',
        'Montserrat' => 'Montserrat',
        'Nunito' => 'Nunito',
        'Open Sans' => 'Open Sans',
        'Optima' => 'Optima',
        'Poppins' => 'Poppins',
        'Roboto' => 'Roboto',
        'Segoe UI' => 'Segoe UI',
        'Source Sans Pro' => 'Source Sans Pro',
        'Tahoma' => 'Tahoma',
        'Trebuchet MS' => 'Trebuchet MS',
        'Ubuntu' => 'Ubuntu',
        'Verdana' => 'Verdana',

        // Serif Fonts
        'American Typewriter' => 'American Typewriter',
        'Baskerville' => 'Baskerville',
        'Big Caslon' => 'Big Caslon',
        'Bodoni MT' => 'Bodoni MT',
        'Bookman Old Style' => 'Bookman Old Style',
        'Cambria' => 'Cambria',
        'Cochin' => 'Cochin',
        'Constantia' => 'Constantia',
        'Copperplate' => 'Copperplate',
        'Didot' => 'Didot',
        'Garamond' => 'Garamond',
        'Georgia' => 'Georgia',
        'Goudy Old Style' => 'Goudy Old Style',
        'Hoefler Text' => 'Hoefler Text',
        'Iowan Old Style' => 'Iowan Old Style',
        'Libre Baskerville' => 'Libre Baskerville',
        'Lora' => 'Lora',
        'Lucida Bright' => 'Lucida Bright',
        'Merriweather' => 'Merriweather',
        'Noto Serif' => 'Noto Serif',
        'Palatino' => 'Palatino',
        'Perpetua' => 'Perpetua',
        'Playfair Display' => 'Playfair Display',
        'PT Serif' => 'PT Serif',
        'Rockwell' => 'Rockwell',
        'Source Serif Pro' => 'Source Serif Pro',
        'Times New Roman' => 'Times New Roman',

        // Monospace Fonts
        'Andale Mono' => 'Andale Mono',
        'Consolas' => 'Consolas',
        'Courier New' => 'Courier New',
        'Fira Code' => 'Fira Code',
        'IBM Plex Mono' => 'IBM Plex Mono',
        'JetBrains Mono' => 'JetBrains Mono',
        'Lucida Console' => 'Lucida Console',
        'Lucida Sans Typewriter' => 'Lucida Sans Typewriter',
        'Monaco' => 'Monaco',
        'Roboto Mono' => 'Roboto Mono',
        'Source Code Pro' => 'Source Code Pro',
        'Space Mono' => 'Space Mono',

        // Display & Handwritten Fonts
        'Abril Fatface' => 'Abril Fatface',
        'Anton' => 'Anton',
        'Archivo Black' => 'Archivo Black',
        'Bebas Neue' => 'Bebas Neue',
        'Caveat' => 'Caveat',
        'Comfortaa' => 'Comfortaa',
        'Comic Sans MS' => 'Comic Sans MS',
        'Cookie' => 'Cookie',
        'Courgette' => 'Courgette',
        'Dancing Script' => 'Dancing Script',
        'Fredoka One' => 'Fredoka One',
        'Great Vibes' => 'Great Vibes',
        'Indie Flower' => 'Indie Flower',
        'Kaushan Script' => 'Kaushan Script',
        'Lobster' => 'Lobster',
        'Oswald' => 'Oswald',
        'Pacifico' => 'Pacifico',
        'Patrick Hand' => 'Patrick Hand',
        'Permanent Marker' => 'Permanent Marker',
        'Play' => 'Play',
        'Press Start 2P' => 'Press Start 2P',
        'Raleway' => 'Raleway',
        'Righteous' => 'Righteous',
        'Sacramento' => 'Sacramento',
        'Shadows Into Light' => 'Shadows Into Light',
        'Special Elite' => 'Special Elite',
        'Uncial Antiqua' => 'Uncial Antiqua',
        'Yellowtail' => 'Yellowtail',

        // More Google Fonts - Sans-Serif
        'Asap' => 'Asap',
        'Barlow' => 'Barlow',
        'Cabin' => 'Cabin',
        'Catamaran' => 'Catamaran',
        'Dosis' => 'Dosis',
        'Exo 2' => 'Exo 2',
        'Hind' => 'Hind',
        'IBM Plex Sans' => 'IBM Plex Sans',
        'Josefin Sans' => 'Josefin Sans',
        'Karla' => 'Karla',
        'Manrope' => 'Manrope',
        'Maven Pro' => 'Maven Pro',
        'Muli' => 'Muli',
        'Noto Sans' => 'Noto Sans',
        'Overpass' => 'Overpass',
        'Oxygen' => 'Oxygen',
        'Prompt' => 'Prompt',
        'PT Sans' => 'PT Sans',
        'Quicksand' => 'Quicksand',
        'Red Hat Display' => 'Red Hat Display',
        'Rubik' => 'Rubik',
        'Signika' => 'Signika',
        'Slabo 27px' => 'Slabo 27px',
        'Titillium Web' => 'Titillium Web',
        'Varela Round' => 'Varela Round',
        'Work Sans' => 'Work Sans',
        'Yantramanav' => 'Yantramanav',

        // More Google Fonts - Serif
        'Alegreya' => 'Alegreya',
        'Amiri' => 'Amiri',
        'Arvo' => 'Arvo',
        'Bitter' => 'Bitter',
        'Cardo' => 'Cardo',
        'Cormorant Garamond' => 'Cormorant Garamond',
        'Crimson Text' => 'Crimson Text',
        'Domine' => 'Domine',
        'EB Garamond' => 'EB Garamond',
        'Fauna One' => 'Fauna One',
        'Gentium Book Basic' => 'Gentium Book Basic',
        'IM Fell English' => 'IM Fell English',
        'Inknut Antiqua' => 'Inknut Antiqua',
        'Josefin Slab' => 'Josefin Slab',
        'Kreon' => 'Kreon',
        'Neuton' => 'Neuton',
        'Noticia Text' => 'Noticia Text',
        'Old Standard TT' => 'Old Standard TT',
        'Oranienbaum' => 'Oranienbaum',
        'Philosopher' => 'Philosopher',
        'Poly' => 'Poly',
        'Prata' => 'Prata',
        'Quattrocento' => 'Quattrocento',
        'Radley' => 'Radley',
        'Rasa' => 'Rasa',
        'Roboto Slab' => 'Roboto Slab',
        'Rozha One' => 'Rozha One',
        'Slabo 13px' => 'Slabo 13px',
        'Spectral' => 'Spectral',
        'Taviraj' => 'Taviraj',
        'Tinos' => 'Tinos',
        'Trirong' => 'Trirong',
        'Ultra' => 'Ultra',
        'Vidaloka' => 'Vidaloka',
        'Volkhov' => 'Volkhov',
        'Vollkorn' => 'Vollkorn',
        'Zilla Slab' => 'Zilla Slab',
    ],
];
